### PR TITLE
fixed "npm run test"

### PR DESCRIPTION
**Pull request by adietish**
standupServiceTest.ts was not fixed, just being able to run the tests
via npm run test was.

Signed-off-by: Andre Dietisheim <adietish@redhat.com>

### CODE REVIEW

**Comment by adietish** [comment]
@gorkem please review

**Comment by adietish** [comment]
@gorkem dare to review please?

**Comment by adietish** [comment]
@gorkem dare to review please?

**Comment by gorkem** [comment]
This is what I get when I try the branch

```
> penfold@0.0.0 test /Users/gercan/workspaces/penfold
> ./node_modules/mocha/bin/mocha tests/**/*.ts --reporter spec --require ts-node/register

Error: Cannot find module 'hubot'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)

```

**Comment by adietish** [comment]
@gorkem maybe this was caused by the branch not being rebased? I get the following:
```
npm test

> penfold@0.0.0 test /Users/adietish/Documents/jboss-workspaces/penfold
> ./node_modules/mocha/bin/mocha tests/**/*.ts --reporter spec --require ts-node/register



  Standup service
[Mon Dec 10 2018 15:15:53 GMT+0100 (Central European Standard Time)] DEBUG Loading adapter null
[Mon Dec 10 2018 15:15:53 GMT+0100 (Central European Standard Time)] ERROR Cannot load adapter null - Error: Cannot find module 'hubot-null'
npm ERR! Test failed.  See above for more details.
```
It compiles and run, but then the test fails which is expected: i just wanted to fix the testing infrastructure, I didnt fix the test (yet)

**Comment by gorkem** [comment]
Did you close this on purpose ?

**Comment by adietish** [comment]
@gorkem no, I rebased and pushed force which resulted in this having 0 changes: looks like you merged it before I rebased?

**Pull request closed without merging**
