### PR TITLE
Issue 11: remind all standups

### PR DESCRIPTION
**Pull request by adietish**
this fixes https://github.com/gorkem/penfold/issues/11

### CODE REVIEW

**Comment by adietish** [comment]
@gorkem please review

**Comment by adietish** [comment]
@gorkem any progress? would be awesome if we could get any further here.

**Comment by gorkem** [comment]
@adietish can you rebase this one, I think the builds should start working

**Comment by adietish** [comment]
@gorkem rebased.

**Comment by adietish** [comment]
@gorkem unfortunately builds seem not to work yet, url says that it's unconfigured:
```http://unconfigured-jenkins-location/job/gorkem/job/penfold/job/PR-12/6/display/redirect```

**Comment by adietish** [comment]
@gorkem have a bit of time to look into this PR please?

**Pull request merged**
